### ISSUE TITLE
Installation dependencies, relative import error

### ISSUE THREAD

**Issue by tvwenger** [PrincetonUniversity/astro-tigress#4]
Following the installation instructions in `install.sh`, I did the following:

```bash
git clone git@github.com:PrincetonUniversity/astro-tigress.git
cd astro-tigress
conda create --name astro-tigress python=3.8 poetry jupyterlab xarray
conda activate astro-tigress
poetry install
```
which results in the error: `Poetry could not find a pyproject.toml file in /home/twenger/science/python/astro-tigress or its parents`. Indeed, this project does not include a `pyproject.toml` file.

I have managed to install the package by creating a `setup.py`, like: 

```python
from setuptools import setup

with open("requirements.txt") as f:
    install_requires = f.read().splitlines()

setup(
    name="astro-tigress",
    version="1.0",
    description="",
    author="",
    author_email="",
    packages=["astro_tigress"],
    install_requires=install_requires,
    package_data={"astro_tigress": ["coolftn.txt"]},
)
```

which allows the package to be installed via

```bash
git clone git@github.com:PrincetonUniversity/astro-tigress.git
cd astro-tigress
conda create --name astro-tigress python=3.8 pip
conda activate astro-tigress
pip install .
```

I am unable to import the package, however, due to a `ModuleNotFoundError`:
```
>>> import astro_tigress
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/twenger/science/python/astro-tigress/astro_tigress/__init__.py", line 6, in <module>
    from astro_tigress.tigress_read import Model, DataMHD, DataRad, DataChem, DataCO
  File "/home/twenger/science/python/astro-tigress/astro_tigress/tigress_read.py", line 7, in <module>
    from . import ytathena as ya
  File "/home/twenger/science/python/astro-tigress/astro_tigress/ytathena.py", line 12, in <module>
    import const
ModuleNotFoundError: No module named 'const'
```

The issue is due to a relative import problem. I will submit a PR to fix.

**Comment by changgoo** [comment]
closed by #5
